name: primer test
on:
  push:
    branches: ["updates"]
  pull_request:
    branches: ["updates"]
permissions:
  contents: read
jobs:
  backend:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python 3.12
        uses: actions/setup-python@v3
        with:
          python-version: "3.12"
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install flake8 pytest
          pip install -r Backend/requirements.txt
      - name: Lint with flake8
        run: |
          # stop the build if there are Python syntax errors or undefined names
          flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
          # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
          flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
      - name: check linting
        working-directory: Backend
        run: ruff check .
      - name: SonarCloud Scan
        uses: SonarSource/sonarcloud-github-action@v2
        with:
          projectBaseDir: .
          args: >
            -Dsonar.projectKey=TU_PROYECTO_KEY
            -Dsonar.organization=TU_ORG
            -Dsonar.python.version=3.12

            - name: Test with pytest
              working-directory: Backend
              run: pytest

  frontend:
    name: Frontend (Angular)
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: Install Node dependencies
        run: npm install --prefix frontend

      - name: Lint Angular
        run: npm run lint --prefix frontend

      - name: Build Angular
        run: npm run build --prefix frontend

      - name: check linting
        working-directory: frontend
        run: ruff check .
  sonar:
    sonarqube:
      name: SonarQube
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v4
          with:
            fetch-depth: 0
        - name: SonarQube Scan
          uses: SonarSource/sonarqube-scan-action@v2
          with:
            projectBaseDir: .
            args: >
              -Dsonar.projectKey=MoralesBilli_proyecto-tads-ci
              -Dsonar.organization=moralesbilli
              -Dsonar.python.version=3.12
          env:
            SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
